# Defines object locations as [x, y, theta] in the robot's frame for a bunch of tasks
# --- MoveTo ---
Station A: [3.0, -1.0, 0.0]
Station B: [1.0, 1.0, 0.0]
Station C: [2.0, 1.0, 0.0]
Station D: [3.0, 1.0, 0.0]
Parking: [-1.0, -1.0, 0.0]
Aruco Stand: [-1.6, 3.0, 0.0]
# --- MoveToWithTimeout ---
Point A: [3.0, -1.0, 0.0]
Point B: [1.8, -1.2, 0.0]
Point C: [1.0, -1.0, 0.0]
